services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    command: mongod --quiet --logpath /dev/null # Deshabilitar logs de mongo

  token-service:
    build: ./services/token_service
    ports:
      - '4000:4000'

  auth-service:
    build: ./services/auth_service
    ports:
      - '3006:3006'
    env_file:
      - ./services/auth_service/.env

  user-service:
    build: ./services/user_service
    ports:
      - '3001:3001'
    env_file:
      - ./services/user_service/.env
    depends_on:
      - mongodb

  delivery-service:
    build: ./services/delivery_service
    ports:
      - '3002:3002'
    depends_on:
      - mongodb

  stock-service:
    build: ./services/stock_service
    ports:
      - '3003:3003'
    env_file:
      - ./services/stock_service/.env
    depends_on:
      - mongodb
      - store-service

  store-service:
    build: ./services/store_service
    ports:
      - '3004:3004'
    env_file:
      - ./services/store_service/.env
    depends_on:
      - mongodb

  owner-service:
    build: ./services/owner_service
    ports:
      - '3005:3005'
    env_file:
      - ./services/owner_service/.env
    depends_on:
      - mongodb
  sale-service:
    build: ./services/sale_service
    ports:
      - '3007:3007'
    env_file:
      - ./services/sale_service/.env
    depends_on:
      - mongodb

  deliveryman-service:
    build: ./services/deliveryman_service
    ports:
      - '3008:3008'
    env_file:
      - ./services/deliveryman_service/.env
    depends_on:
      - mongodb

  analytics-service:
    build: ./services/analytics_service
    ports:
      - '3009:3009'
    env_file:
      - ./services/analytics_service/.env
    depends_on:
      - sale-service
      - store-service

  api-gateway:
    build: ./api_gateway
    ports:
      - '3000:3000'
    env_file:
      - ./api_gateway/.env
    depends_on:
      - token-service
      - auth-service
      - user-service
      - delivery-service
      - stock-service
      - store-service
      - owner-service
      - sale-service
      - deliveryman-service
      - analytics-service
